### ISSUE TITLE
Error occurs "symbol’s function definition is void: file-contents" when calling gkh-org-table-display

### ISSUE THREAD

**Issue by lyjdwh** [Kinneyzhang/gk-habit#1]
emacs 27.1

using `org-file-contents` replace `file-contents` works!

**Comment by Kinneyzhang** [comment]
Oops, ```file-contents``` is a function defined in my personal emacs congfiguration and I forgot it. Have fix it, thanks!

Actually, ```gkhabit.el``` is a tentative emacs package and I may not give it cares in the future.
